Dockerfile
evaluator.go
go.mod
go.sum
main.go
serve.go
serve_unix.go
serve_windows.go
vhs.go
video.go

* Ability to customize the VHS instance when running the evaluator.
* Check and log errors
* Refactor code
* Run the server as a different user and deescalate permissions (when supplying a GID & UID).

Harden the Docker image

---

README.md

docs: fix arch install instructions

---

README.md
serve.go

feat: authorized keys

---

README.md

docs: add server settings

---

evaluator.go
vhs.go

fix: leakless windows fix

---

evaluator.go
examples/demo.gif
main.go

fix: error if dimensions are too small

---

examples/cli-ui/README.md
examples/commands/README.md
examples/gh-cli/README.md
examples/glow/README.md
examples/gum/README.md
examples/jqp/README.md
examples/neofetch/README.md
examples/settings/README.md
examples/slides/README.md

Fixes #81
- docs(examples): cli-ui readme
- docs(examples): gh cli readme
- docs(examples): glow readme
- docs(examples): gum readme
- docs(examples): jqp readme
- docs(examples): neofetch readme
- docs(examples): slides readme
- docs(examples): settings readme
- docs(examples): commands readme

Example READMEs

---

tty.go

fixes #93
can someone on windows test?

fix: use cmd as default on windows

---

vhs.go

Avoids nested ifs, simplifies interval & timeout handling.

chore: simplify vhs.Record

---

README.md

Changed **README.md** to include installation instructions with Scoop, a command line package manager for Windows.

Added Scoop Installation instructions to README.md

---

examples/neofetch/colorize-ascii.go
go.mod
go.sum
main.go
record.go
record_test.go
token.go

This PR allows users to automatically write `.tape` files by recording their terminal.
To use simply:
```
vhs record > myrecording.tape
```
Then, use the terminal as you wish. VHS will record commands, typing, and
sleeps and write them to a tape file.
Once the tape file is written, you may want to tweak it manually before
running:
```
vhs < myrecording.tape
```

VHS Record Feature (`vhs record`)

---

go.mod
go.sum
main.go
publish.go

Publish GIF images to our `vhs.charm.sh` hosting.
* Add `publish` command
* Add `--publish` flag

feat: publish gifs

---

serve.go

We need to wait for the listener to finish and clean up, otherwise we terminate active connections by returning from the serve command.

fix: wait for ssh.Serve to terminate

---

examples/fixtures/all.tape
lexer.go

feat(lexer): backticks act as strings

---

Dockerfile

use debian for docker instead of alpine

---

examples/publish/cassette.tape
examples/publish/output.gif
examples/publish/publish.gif
examples/publish/publish.tape
main.go
publish.go
vhs.go

Publish GIFs tip (when `VHS_PUBLISH`) is not set.

Message about publishing GIFs

---

record.go

fix(record): use backticks if a string contains double and single quotes

---

record.go

Fixes #191
Filters out cursor and OSC query responses.

fix: filter out cursor / OSC query responses

---

README.md

Depends on:
- https://github.com/Homebrew/homebrew-core/pull/114935
- https://github.com/Homebrew/homebrew-core/pull/113517

docs(readme): fix brew installation instructions

---

main.go
publish.go
record.go
vhs.go
video.go

Adds `--quiet` flag for quiet output.

feat: add loglevel flag for silent output

---

main.go
record.go

Fixes https://github.com/charmbracelet/vhs/issues/255

Use user shell for VHS record

---

record.go

Fixes https://github.com/charmbracelet/vhs/issues/293

fix: output tape to stdout

---

command.go
parser.go

feat: `Alt+Enter`

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml
themes_test.go

When checking the project on [Go report card](https://goreportcard.com/report/github.com/charmbracelet/vhs), an ineffectual assignment is reported. This PR fixes this issue.

Theme test: fix ineffectual assignment

---

themes_test.go

I was writing some tests for suggestions in Skate and figured while I'm at it I can write some similar tests for VHS themes since it also uses levenshtein distance for suggestions.

test: add more test cases for suggestions

---

.github/dependabot.yml

build: dependabot update groups

---

README.md

- docs: add publish info to README
- fix(docs): grammar stuff

docs: add vhs publish info to README

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml

Upgrades to the most recent release of Go
for the lint jobs.

chore(ci/lint): update to latest Go

---

README.md

First of all, thank you for this project! I've been using it extensively and couldn't be happier about it.
As per title, I (quickly) documented the `Source` command, I can add more docs if you have any pointers otherwise feel free to edit. 
It's a very helpful command and I was about to open an issue to suggest this feature when I found out it's already there (pleasant surprise) :)

docs: document source command

---

go.mod
go.sum

refs https://github.com/charmbracelet/log/pull/111

fix: update log dep

---

.github/workflows/goreleaser.yml
.github/workflows/nightly.yml

signs and notarizes macos binaries on releases and nightlies

ci: sign & notarize macos binaries

---

README.md

Hey all, 
Big fan of VHS (and Charm in general)!
Wanted to propose a small change to the "Cleanup" example.
I was scratching my head trying to figure out why my tape wasn't actually deleting the file, then realized it was missing the "Enter", so I thought it was worth clarifying in the readme.

docs: add "Enter" to cleanup example
