lexer.go
Fixes #80
Closes #90
Don't double count new lines on windows.
=> fix(lexer): don't double count newlines on windows

main.go
If I'm not mistaken, we require ttyd 1.7.2?
=> fix: require ttyd 1.7.2

main.go
We handle and print errors in main. Disable cobra's own error printing so they don't show up twice.
=> fix: don't print errors twice

evaluator.go, vhs.go
This prevents the render goroutine from directly printing to stdout and ensures a controlled tear-down.
=> chore: use a context to control the recording process

tty.go, tty_unix.go, tty_windows.go
Using `cmd` instead of `powershell` leads to a strange render:
I also see no reason to set default shell in runtime.
This pull request fixes this, and leaves the option to use the tool on older versions.
=> feat: use powershell as default shell on windows>=10 + compile-time optimizations

evaluator.go, main.go, serve.go
This makes vhs jobs cancelable and removes the need for a separate signal handler in the serve command.
It is a slight behavioral change however: we now actively cancel ongoing connections when the sever gets asked to terminate. I intend to address this in a separate PR which sets a timeout for incoming connections.
=> feat: allow external context to be passed to Evaluate

evaluator.go, vhs.go
This ensures canceled jobs will always clean up temporary files on teardown.
=> fix: split up video rendering & cleanup

vhs.go
Fixes a potential race between the total frame counter being updated and vhs.Record signalling it's done.
=> fix: record total frame counter before closing channel

vhs.go
Prevents the entire process from being terminated ungracefully.
=> fix: never os.Exit, let the error bubble up the stack

.gitattributes, examples/images/bubbletea.png, examples/images/glamour.png, examples/images/gum.png, examples/images/harmonica.png, examples/images/images.tape, examples/images/lipgloss.png, examples/images/melt.png, examples/images/skate.png, examples/images/soft-serve.png, examples/images/wish.png, tty.go
Enable sixel on ttyd (note: this commit does not make the images appear in the GIF)
This PR allows ttyd / xterm to support sixel but does not yet solve VHS support
(yet).
This is because the images are rendered on a separate canvas that we'll need to
capture in order to support.
=> enable sixel on ttyd (note: this does not make them appear in the GIF)

examples/settings/set-shell-bash.gif, examples/settings/set-shell-bash.tape, examples/settings/set-shell-zsh.gif
=> fix(examples): output file name

command.go, main.go, themes.go, themes_test.go
This is a bit of an edge case, as the themes.json file is embedded and technically should never fail to parse, but even then it's probably a bad idea to tear down the entire process without any deferred cleanups.
=> fix: never os.Exit, return error

shell.go, tty_windows.go
pwsh is only added on newer versions of PowerShell which might not be pre-installed in Windows 10
=> fix(pwsh): add powershell shell

shell.go
Properly escape powershell/pwsh prompts
Fixes: b0c663c9bc80 ("fix(pwsh): add powershell shell")
=> fix: powershell prompt

serve.go
Partially resolves #59
I still think it would be nice to allow sending back an archive, but for now this will suffice.
One question is how do we define priority? e.g. a tape file has outputs for multiple formats, which should be chosen?
Currently based on this PR, it would be `mp4` -> `webm` -> `gif` (default)
=> feat: allow alternative outputs for serve

main.go, video.go
Allow `Output` location to be overridden by CLI flags:
Specify multiple outputs in the same flag.
```bash
vhs demo.tape --output out.gif,out.webm
```
Pass multiple flags (with shorthand):
```bash
vhs demo.tape -o out.gif -o out.webm
```
Note: this will override any `Output` commands set in the tape file.
=> feat: allow --output to override output location

vhs.go
This PR adds an environment variable to enable [go-rod's no-sandbox option](https://github.com/go-rod/rod/blob/611fbdd4e29fedc18478586057ea293847da317d/lib/launcher/launcher.go#L228).
This was suggested by the go-rod maintainer in the following issue: https://github.com/charmbracelet/vhs/issues/45#issuecomment-1296121300
I know the issue is closed but I couldn't find any other way to integrate vhs in a docker build process like for example with the following Dockerfile:
```Dockerfile
FROM ghcr.io/charmbracelet/vhs
COPY <<EOF hello.tape
Output hello.gif
Type "echo test"
Sleep 500ms
Enter
Sleep 1s
EOF
RUN vhs hello.tape
```
When running with this patch it works when setting the newly added environment variable:
```Dockerfile
FROM ghcr.io/brumhard/vhs:0.0.4
ENV VHS_NO_SANDBOX="true"
COPY …
```
=> feat: env var to optionally set go-rod no-sandbox

video.go
Fixes poor error message when directory doesn't exist for output.
=> fix: ensure directory is present before creating output

examples/settings/set-shell-bash.gif, examples/settings/set-shell-fish.gif, examples/settings/set-shell-zsh.gif, shell.go
assuming that probably in https://github.com/charmbracelet/vhs/issues/39 the problem is zsh is using the user/rc config, this should prevent that.
also did the same for bash and fish.
=> fix: zsh, bash and fish: do not use user/system rcs

examples/welcome.gif, main.go
Fixes https://github.com/charmbracelet/vhs/issues/207
Running `vhs` without arguments should display help instead of waiting for `stdin`.
=> fix: running vhs without arguments or stdin should display help

tty.go
Fix issue #226 by configuring `ttyd` to only listen on `127.0.0.1`
Using the Dockerfile I built my own image with a `vhs` binary built from my branch.
I could successfully create a gif from a tape file:
```
➜  vhs git:(ttyd-localhost-only) ✗ docker run --rm -v $PWD:/vhs c06c63cefe39 demo.tape
File: demo.tape
Host your GIF on vhs.charm.sh: vhs publish <file>.gif
Output .gif demo.gif
Set FontSize 46
Set Width 1200
Set Height 600
Type echo 'Welcome to VHS!'
Sleep 500ms
Enter 1
Sleep 5s
Creating demo.gif...
```
I could also create a gif using `vhs serve`:
```
➜  tapes git:(ttyd-localhost-only) ✗ docker run --rm -p 1976:1976 -v $PWD:/vhs c06c63cefe39 serve
2023/02/14 21:59:26 Starting SSH server on 0.0.0.0:1976
2023/02/14 21:59:26 Starting server with GID: 1976, UID: 1976
2023/02/14 21:59:46 …
```
=> ttyd listens on loopback interface only

evaluator.go, tty.go, vhs.go
- moved the startup code to a `start` function
- `launcher.Lookpath` is ok to return empty, rod downloads the browser if `bin` is empty
- `StartTTYD` did not start `ttyd`
- do not eat `ttyd` startup errors
=> fix: split start into new function

tty.go
From the help:
>     -o, --once              Accept only one client and exit on disconnection
This might be useful if, for example, VHS gets killed for reason and can't clean up after itself, this will guarantee that the ttyd session is also finished, so no one can connect to a dangling ttyd afterwards.
=> fix: ttyd --once

shell.go
hello guys :wave: :yum: 
i'm a [`nushell`](https://www.nushell.sh) user and i'm trying to record a session for the shell
```bash
'
Output out.gif
Set Shell nu
Set TypingSpeed 100ms
Sleep 500ms
Type "ls | where type == file and size > 10Kb | get name"
Sleep 500ms
Enter
Sleep 5s
' | vhs
```
> **Note**
> this is all written in `nushell` :+1: 
when i run this, i can see `bash` launching first, then run `nu` from `bash` and finally drop in `nushell`.
i had a look at `shell.go` and couldn't see `nushell` in the list of supported shells, so i thought i could add it to drop directly inside `nushell` :yum: 
> **Note**
> i've search for `fish` in the source base and `shell.go` is the only non-test source file i found :yum: 
- mirrors the other supported shells
- adds `nushell` which runs `nu …
=> add `nushell` to the list of supported shells

man.go
After executing `vhs` I realized some commands were missing.
I've added them to `man.go` file.
=> docs: add missing commands in man

tty.go
`cmd.Env()`, at that point, is empty, so we're missing all user environment variables...
Since we don't have a way to tell VHS which envs to allow, we should probably keep all of them.
This was working at some point, I think I might have broken it while refactoring the shell init stuff.
=> fix: use os.Environ()

README.md, examples/demo.tape, parser.go
Currently, the documentation only mentions two of the four possible `WindowBar` styles. This PR fixes that.
It is true that the `*Right` styles will be used less than the default styles, but we probably still want to mention them in the docs.
=> docs: Added ColorfulRight and RingsRight

shell.go
Fix #289 in [`shell.go` file](https://github.com/charmbracelet/vhs/blob/main/shell.go).
Remove `-Login` parameter because [official documentation hasn't it](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#syntax).
After removing `-Login` command `vhs` stacks on `Set Shell powershell` instruction. Fix this by changing `-Command` parameter.
**Example `.tape` file:** 
```
Output "demo.gif"
Set Shell powershell
Type "echo 'test'"
Sleep 500ms
Enter
Sleep 2s
```
**Fixed output:**
=> fix: powershell run command

record.go, record_test.go
Fix the issue described in #287 when record writes duration in unsupported units by keeping it in seconds if sleep was more than 1min
=> fix: record sleep only in supported time units

shell.go
When setting colour in the fish shell using `$(set_color ...)` design, we get an error `fish: $(...) is not supported` in the output gif file.
This PR fixes this error. The colours are now set according to the fish shell documentation:
https://fishshell.com/docs/current/cmds/set_color.html#examples
The `demo.tape` was used for testing:
```elixir
Output demo.gif
Set FontSize 24
Set Width 1200
Set Height 600
Set Shell fish
Type "flutter create --platforms=linux example"
Sleep 500ms
Enter
Sleep 5s
```
Bug example:
Example after fixing the bug:
Environment:
```sh
~ $ fish --version
fish, version 3.3.1
~ $ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian …
```
=> fix: set color in fish shell using correct syntax

.gitattributes
this will hint linguist to properly highlight tape files as elixir (like we do in the readme).
Once linguist supports tape files natively, we can remove this :)
=> fix: hint linguist to highlight tape files as elixir

command.go, vhs.go
This PR adds font fallback to Apple Symbols which allows braille characters to
be rendered without empty circles.
=> feat: add Apple Symbols font fallback for braille characters

examples/demo.tape, main.go
- added missing `Escape` to embedded tape
- replace the default `examples/demo.gif` to the given name plus `.gif` ext
=> feat: improve vhs new

main.go
Closes #359
There were already OS-specific files defining a sane shell to use so `ensureDependencies` uses that instead of hardcoding `bash` for all platforms.
=> fix: Check defaultShell dependency

shell.go
Since Nushell version 0.83, the `let-env` command has been [removed](https://www.nushell.sh/blog/2023-07-25-nushell_0_83.html#breaking-changes).
This breaks VHS when recording `nu` tapes.
Replace `let-env VAR` with `$env.VAR`
Also the --interactive command is redundant, since the --execute flag also starts the interactive mode
=> Fix VHS for Nushell version ^0.83

.github/workflows/lint.yml, go.mod
Runs 'go mod tidy' and checks in the result.
To ensure that the go.mod and go.sum remain tidy,
adds a new lint job that will fail if the files change
after running 'go mod tidy'.
=> chore: go mod tidy, and keep it tidy

command.go
golangci-lint currently fails on main with:
```
command.go:6: File is not `goimports`-ed (goimports)
"github.com/atotto/clipboard"
command.go:267:1: exported: exported function ExecuteCopy should have comment or be unexported (revive)
func ExecuteCopy(c Command, _ *VHS) {
^
command.go:271:1: exported: exported function ExecutePaste should have comment or be unexported (revive)
func ExecutePaste(_ Command, v *VHS) {
^
```
This fixes all three issues.
=> chore: Fix lint on main

themes.json
The base16 themes--including tomorrow, tomorrow-night, and tomorrow-night-eighties--are now maintained by tinted-theming at https://github.com/tinted-theming/base16-schemes.
Let's update these 3 themes to match their schemes based on the base16 styling guidelines: https://github.com/tinted-theming/base17/blob/main/styling.md
<details>
<summary>Tomorrow</summary>
https://github.com/charmbracelet/vhs/assets/1639061/edc56537-1094-4e78-b773-0020ee5f0c33
https://github.com/charmbracelet/vhs/assets/1639061/9213f33d-058b-4237-9fb3-f3b8d924d7f1
</details>
<details>
<summary>Tomorrow Night</summary>
https://github.com/charmbracelet/vhs/assets/1639061/68071d0f-3be3-41a7-9d01-453d99e3ceb3
https://github.com/charmbracelet/vhs/assets/1639061/3c061a05-fc86-47fd-81c4-f98eb056f983
</details>
<details> …
=> Fix tomorrow themes

command.go, parser.go, parser_test.go
I'd like to record tapes that can type Ctrl+Space to trigger a keybinding I have in tmux. I could achieve this by remapping the keybinding temporarily for VHS, but it was nearly as easy to just make this PR instead.
A similar change was made recently in https://github.com/charmbracelet/vhs/commit/b5f8be82aec8d538bd00149985fdb9dfa50e5d4f to allow Ctrl+Shift+Alt+Enter, so I figured this might also be acceptable.
=> Allow Ctrl+Space

README.md
When using the `Type` command you can enclose the text with either a single quote, double quote, or backtick character. However, the readme only provides examples of the double quote character which leads to issues like https://github.com/charmbracelet/vhs/issues/356.
This fixes https://github.com/charmbracelet/vhs/issues/356 by adding an examples with backticks and single quotes.
=> docs: Update README.md to include backticks and single quotes

record.go, record_test.go
I found the issue while testing a low value of 5ms for `sleepThreshold`
The goal was to create the same delays as what I actually type.
Here is some related comments ->  
https://news.ycombinator.com/item?id=39298134
Here is the stacktrace you would get without the fix:
```
panic: runtime error: index out of range [634] with length 634
goroutine 1 [running]:
main.inputToTape({0xc0004d8000?, 0xc00014c000?})
/Users/username/Documents/vhs/record.go:153 +0x15d8
main.Record(0xc000118700?, {0x285e9e0?, 0x4?, 0x1c2156c?})
/Users/username/Documents/vhs/record.go:117 +0x613
github.com/spf13/cobra.(*Command).execute(0x280c140, {0x285e9e0, 0x0, 0x0})
/Users/username/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x280ccc0) …
```
=> Fix app crash when there is repeated SLEEP at the end of the "lines" slice

README.md, command.go, command_test.go, evaluator.go, examples/demo.gif, parser/parser.go, token/token.go
Implements https://github.com/charmbracelet/vhs/issues/419
```haskell
Output examples/demo.gif
Env PROMPT "〉"
Require echo
Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600
Type "echo 'Welcome to VHS!'" Sleep 500ms  Enter
Sleep 5s
```
and also allows adding environment variables.
```haskell
Env TESTING "this works"
Type "echo $TESTING"
Enter
Sleep 3s
```
=> cmd: add support for `ENV` command

command.go
This fixes a typo in Shift+Tab command. The command was pressing ShiftLeft and releasing AltLeft.
=> Release ShiftLeft in Shift+Tab

record.go
Set the environment variable VHS_RECORD=true in the spawned pty command
to allow processes to detect if it is running in a real TTY or in a VHS
recording. Certain TUI libraries query the terminal for feature
detection which can cause issues when running within a VHS pty. Setting this environment variable allows processes to detect if they are running in VHS and enable/disable features as needed.
=> record: set VHS_RECORD=true environment variable in process

.gitignore, command.go, evaluator.go, testing.go, vhs.go
Updates command functions to return errors when unable to continue.
- Many silently ignored errors are now reported
- Fixed a race condition where some early SET commands would fail to access `term` if it hadn't started yet.
Dependency of #257 to address the concern of stopping/bubbling up if an error occurs without resorting to panic https://github.com/charmbracelet/vhs/pull/257#issuecomment-1878088189
=> Command err handling

evaluator.go
This PR adds a warning when using the `SET` commands after the top declaration.
> Agreed, if a setting is ignored we should display a warning that this setting should appear at the top of the file!
> _Originally posted by @maaslalani in https://github.com/charmbracelet/vhs/issues/503#issuecomment-2241697926_
=> feat: warn when using `SET` commands not being the top decl

parser/parser.go
👋  Hello!
This corrects a typo in the WindowBar parser. fixes #543 
Tested locally:
```
$ vhs test.tape
File: test.tape
3 │ Set WindowBar RingsRight
^^^^^^^^^^ RingsRight is not a valid bar style.
parser: 1 error(s)
recording failed
```
```
./vhs ./test.tape
File: ./test.tape
Output .gif demo.gif
Set WindowBar RingsRight
Set FontSize 46
Set Width 1200
Set Height 600
Type echo Welcome to VHS!
Sleep 500ms
Enter 1
Sleep 5s
Creating demo.gif...
Host your GIF on vhs.charm.sh: vhs publish <file>.gif
```
=> Fix typo in WindowBar parser - fixes #543

video.go
If a tape file only asks for text output, e.g., `Output demo.txt`, `vhs` also creates an `out.gif` by default.
This PR removes that behaviour, and only outputs GIF files if `Output <name>.gif` appears in the tape file.
=> feat: don't create 'out.gif' by default

lexer/lexer.go, lexer/lexer_test.go, parser/parser.go, token/token.go
Close #561 
Related https://github.com/charmbracelet/tree-sitter-vhs/pull/23
This PR introduces support to:
```
CTRL+[
CTRL+@
CTRL+^
CTRL+]
CTRL+\
CTRL+-
SHIFT+[
SHIFT+]
ALT+[
ALT+]
```
=> feat: support additional alt/ctrl/shift special characters

record.go
Hello,
This [pr](https://github.com/charmbracelet/vhs/pull/478) broke env variables propagation to terminal spawned by record command.
From Env description
```
// If Env is nil, the new process uses the current process's
// environment.
```
Appending `VHS_RECORD` makes it not nil, so it resets env. This pr fixes #554.
For example with the latest released vhs
```
root# echo $HOME
/var/root
root# vhs record
sh-3.2# echo $HOME
sh-3.2# env
VHS_RECORD=true
PWD=/private/var/root
SHLVL=1
_=/usr/bin/env
```
The simplest solution is to get env of the main process and then append `VHS_RECORD` 
The same example with the build from this PR
```
root# echo $HOME
/var/root
root# ./vhs record
sh-3.2# echo $HOME
/var/root
sh-3.2# env
TERM=xterm-ghostty
SHELL=/bin/sh
LC_ALL=en_US.UTF-8
USER=root …
```
=> fix(record): propagate env of vhs process to record terminal

embed.go, go.mod, go.sum, main.go, parser/parser_test.go, serve_windows.go
so, apparently, since I don't know when, having GOPRIVATE set might make `go get` resolve to a bad sha? 
i don't get why this is happening, but figured out it happened on all my machines because all of them had this env set to `github.com/charmbracelet/`. 
anyway, github actions was resolving correctly apparently.
=> ci: fix build

parser/parser.go
refs #551
refs #567
it was setting the an empty string as argument to all sourced commands.
=> fix: source not respecting arguments of sourced commands
